/left_thumb_3_joint_mimic:
  ros__parameters:
    name:
      antiwindup: false
      d: 0.00033
      i: 0.0123
      i_clamp_max: 0.0123
      i_clamp_min: 0.0001
      p: 0.35
    qos_overrides:
      /clock:
        subscription:
          depth: 1
          durability: volatile
          history: keep_last
          reliability: best_effort
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: true

/left_thumb_4_joint_mimic:
  ros__parameters:
    name:
      antiwindup: false
      d: 0.00033
      i: 0.0123
      i_clamp_max: 0.0123
      i_clamp_min: 0.0001
      p: 0.35
    qos_overrides:
      /clock:
        subscription:
          depth: 1
          durability: volatile
          history: keep_last
          reliability: best_effort
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: true

/left_index_2_joint_mimic:
  ros__parameters:
    name:
      antiwindup: false
      d: 0.0001
      i: 0.05
      i_clamp_max: 0.05
      i_clamp_min: 0.01
      p: 1.0
    qos_overrides:
      /clock:
        subscription:
          depth: 1
          durability: volatile
          history: keep_last
          reliability: best_effort
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: true

/left_middle_2_joint_mimic:
  ros__parameters:
    name:
      antiwindup: false
      d: 0.0001
      i: 0.05
      i_clamp_max: 0.05
      i_clamp_min: 0.01
      p: 1.0
    qos_overrides:
      /clock:
        subscription:
          depth: 1
          durability: volatile
          history: keep_last
          reliability: best_effort
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: true

/left_ring_2_joint_mimic:
  ros__parameters:
    name:
      antiwindup: false
      d: 0.0001
      i: 0.05
      i_clamp_max: 0.05
      i_clamp_min: 0.01
      p: 1.0
    qos_overrides:
      /clock:
        subscription:
          depth: 1
          durability: volatile
          history: keep_last
          reliability: best_effort
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: true

/left_little_2_joint_mimic:
  ros__parameters:
    name:
      antiwindup: false
      d: 0.0001
      i: 0.05
      i_clamp_max: 0.05
      i_clamp_min: 0.01
      p: 1.0
    qos_overrides:
      /clock:
        subscription:
          depth: 1
          durability: volatile
          history: keep_last
          reliability: best_effort
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: true
