controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true
    
    joint_state:
      type: joint_state_broadcaster/JointStateBroadcaster
      joints:
        - left_thumb_1_joint
        - left_thumb_2_joint
        - left_thumb_3_joint
        - left_thumb_4_joint
        - left_index_1_joint
        - left_index_2_joint
        - left_middle_1_joint
        - left_middle_2_joint
        - left_ring_1_joint
        - left_ring_2_joint
        - left_little_1_joint
        - left_little_2_joint

    palm_force_sensor_controller:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster  

    thumb_force_sensor_1_controller:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster  

    thumb_force_sensor_2_controller:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    thumb_force_sensor_3_controller:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster
      
    thumb_force_sensor_4_controller:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    index_force_sensor_1_controller:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    index_force_sensor_2_controller:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    index_force_sensor_3_controller:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster
      
    middle_force_sensor_1_controller:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    middle_force_sensor_2_controller:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster
      
    middle_force_sensor_3_controller:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    ring_force_sensor_1_controller:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    ring_force_sensor_2_controller:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster
      
    ring_force_sensor_3_controller:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster
      
    little_force_sensor_1_controller:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    little_force_sensor_2_controller:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster
      
    little_force_sensor_3_controller:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster
      
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      
joint_trajectory_controller:
  ros__parameters:
    joints:  # 控制关节列表
      - left_thumb_1_joint
      - left_thumb_2_joint
      - left_index_1_joint
      - left_middle_1_joint
      - left_ring_1_joint
      - left_little_1_joint
      
    gains.left_thumb_1_joint.p: 0.12
    gains.left_thumb_1_joint.i: 0.0083
    gains.left_thumb_1_joint.d: 0.0014
    gains.left_thumb_1_joint.i_clamp: 0.2
              
    gains.left_thumb_2_joint.p: 0.56
    gains.left_thumb_2_joint.i: 0.0123
    gains.left_thumb_2_joint.d: 0.00058
    gains.left_thumb_2_joint.i_clamp: 0.2

    gains.left_index_1_joint.p: 1.0
    gains.left_index_1_joint.i: 0.05
    gains.left_index_1_joint.d: 0.0014
    gains.left_index_1_joint.i_clamp: 0.2

    gains.left_middle_1_joint.p: 1.0
    gains.left_middle_1_joint.i: 0.05
    gains.left_middle_1_joint.d: 0.0014
    gains.left_middle_1_joint.i_clamp: 0.2

    gains.left_ring_1_joint.p: 1.0
    gains.left_ring_1_joint.i: 0.05
    gains.left_ring_1_joint.d: 0.0014
    gains.left_ring_1_joint.i_clamp: 0.2

    gains.left_little_1_joint.p: 1.0
    gains.left_little_1_joint.i: 0.05
    gains.left_little_1_joint.d: 0.0014
    gains.left_little_1_joint.i_clamp: 0.2
     
    command_interfaces: [position, velocity]  
    state_interfaces: [position, velocity]   

    # 容差参数
    goal_tolerance:
      position: 0.5
      velocity: 0.5

    # 状态发布频率
    state_publish_rate: 50.0

palm_force_sensor_controller:
  ros__parameters:
    sensor_name: "palm_force_sensor"
    joint: "palm_force_sensor_joint"  
    frame_id: "palm_force_sensor"  
    publish_wrench: true     
    publish_sensor_status: true  
    rate: 100.0
    
thumb_force_sensor_1_controller:
  ros__parameters:
    sensor_name: "thumb_force_sensor_1"
    joint: "thumb_force_sensor_1_joint"  
    frame_id: "thumb_force_sensor_1"  
    publish_wrench: true     
    publish_sensor_status: true  
    rate: 100.0
    
thumb_force_sensor_2_controller:
  ros__parameters:
    sensor_name: "thumb_force_sensor_2"
    joint: "thumb_force_sensor_2_joint"  
    frame_id: "thumb_force_sensor_2"  
    publish_wrench: true     
    publish_sensor_status: true  
    rate: 100.0
    
thumb_force_sensor_3_controller:
  ros__parameters:
    sensor_name: "thumb_force_sensor_3"
    joint: "thumb_force_sensor_3_joint"  
    frame_id: "thumb_force_sensor_3"  
    publish_wrench: true     
    publish_sensor_status: true  
    rate: 100.0
    
thumb_force_sensor_4_controller:
  ros__parameters:
    sensor_name: "thumb_force_sensor_4"
    joint: "thumb_force_sensor_4_joint"  
    frame_id: "thumb_force_sensor_4"  
    publish_wrench: true     
    publish_sensor_status: true  
    rate: 100.0
    
index_force_sensor_1_controller:
  ros__parameters:
    sensor_name: "index_force_sensor_1"
    joint: "index_force_sensor_1_joint"  
    frame_id: "index_force_sensor_1"  
    publish_wrench: true     
    publish_sensor_status: true  
    rate: 100.0
    
index_force_sensor_2_controller:
  ros__parameters:
    sensor_name: "index_force_sensor_2"
    joint: "index_force_sensor_2_joint"  
    frame_id: "index_force_sensor_2"  
    publish_wrench: true     
    publish_sensor_status: true  
    rate: 100.0

index_force_sensor_3_controller:
  ros__parameters:
    sensor_name: "index_force_sensor_3"
    joint: "index_force_sensor_3_joint"  
    frame_id: "index_force_sensor_3"  
    publish_wrench: true     
    publish_sensor_status: true  
    rate: 100.0
    
middle_force_sensor_1_controller:
  ros__parameters:
    sensor_name: "middle_force_sensor_1"
    joint: "middle_force_sensor_1_joint"  
    frame_id: "middle_force_sensor_1"  
    publish_wrench: true     
    publish_sensor_status: true  
    rate: 100.0
    
middle_force_sensor_2_controller:
  ros__parameters:
    sensor_name: "middle_force_sensor_2"
    joint: "middle_force_sensor_2_joint"  
    frame_id: "middle_force_sensor_2"  
    publish_wrench: true     
    publish_sensor_status: true  
    rate: 100.0
    
middle_force_sensor_3_controller:
  ros__parameters:
    sensor_name: "middle_force_sensor_3"
    joint: "middle_force_sensor_3_joint"  
    frame_id: "middle_force_sensor_3"  
    publish_wrench: true     
    publish_sensor_status: true  
    rate: 100.0
    
ring_force_sensor_1_controller:
  ros__parameters:
    sensor_name: "ring_force_sensor_1"
    joint: "ring_force_sensor_1_joint"  
    frame_id: "ring_force_sensor_1"  
    publish_wrench: true     
    publish_sensor_status: true  
    rate: 100.0
    
ring_force_sensor_2_controller:
  ros__parameters:
    sensor_name: "ring_force_sensor_2"
    joint: "ring_force_sensor_2_joint"  
    frame_id: "ring_force_sensor_2"  
    publish_wrench: true     
    publish_sensor_status: true  
    rate: 100.0
    
ring_force_sensor_3_controller:
  ros__parameters:
    sensor_name: "ring_force_sensor_3"
    joint: "ring_force_sensor_3_joint"  
    frame_id: "ring_force_sensor_3"  
    publish_wrench: true     
    publish_sensor_status: true  
    rate: 100.0
    
little_force_sensor_1_controller:
  ros__parameters:
    sensor_name: "little_force_sensor_1"
    joint: "little_force_sensor_1_joint"  
    frame_id: "little_force_sensor_1"  
    publish_wrench: true     
    publish_sensor_status: true  
    rate: 100.0
    
little_force_sensor_2_controller:
  ros__parameters:
    sensor_name: "little_force_sensor_2"
    joint: "little_force_sensor_2_joint"  
    frame_id: "little_force_sensor_2"  
    publish_wrench: true     
    publish_sensor_status: true  
    rate: 100.0
    
little_force_sensor_3_controller:
  ros__parameters:
    sensor_name: "little_force_sensor_3"
    joint: "little_force_sensor_3_joint"  
    frame_id: "little_force_sensor_3"  
    publish_wrench: true     
    publish_sensor_status: true  
    rate: 100.0
