controller_manager:
  ros__parameters:
    update_rate: 100  # 控制器更新频率
    joints:
      - left_thumb_1_joint
      - left_thumb_2_joint
      - left_index_1_joint
      - left_middle_1_joint
      - left_ring_1_joint
      - left_little_1_joint
    command_interfaces: [position, velocity]  
    state_interfaces: [position, velocity]       

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      joints:
        - left_thumb_1_joint
        - left_thumb_2_joint
        - left_thumb_3_joint
        - left_thumb_4_joint
        - left_index_1_joint
        - left_index_2_joint
        - left_middle_1_joint
        - left_middle_2_joint
        - left_ring_1_joint
        - left_ring_2_joint
        - left_little_1_joint
        - left_little_2_joint

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      
joint_trajectory_controller:
  ros__parameters:
    joints:  # 控制关节列表
      - left_thumb_1_joint
      - left_thumb_2_joint
      - left_index_1_joint
      - left_middle_1_joint
      - left_ring_1_joint
      - left_little_1_joint
      
    gains.left_thumb_1_joint.p: 0.12
    gains.left_thumb_1_joint.i: 0.0083
    gains.left_thumb_1_joint.d: 0.0014
    gains.left_thumb_1_joint.i_clamp: 0.2
              
    gains.left_thumb_2_joint.p: 0.56
    gains.left_thumb_2_joint.i: 0.0123
    gains.left_thumb_2_joint.d: 0.00058
    gains.left_thumb_2_joint.i_clamp: 0.2

    gains.left_index_1_joint.p: 1.0
    gains.left_index_1_joint.i: 0.05
    gains.left_index_1_joint.d: 0.0014
    gains.left_index_1_joint.i_clamp: 0.2

    gains.left_middle_1_joint.p: 1.0
    gains.left_middle_1_joint.i: 0.05
    gains.left_middle_1_joint.d: 0.0014
    gains.left_middle_1_joint.i_clamp: 0.2

    gains.left_ring_1_joint.p: 1.0
    gains.left_ring_1_joint.i: 0.05
    gains.left_ring_1_joint.d: 0.0014
    gains.left_ring_1_joint.i_clamp: 0.2

    gains.left_little_1_joint.p: 1.0
    gains.left_little_1_joint.i: 0.05
    gains.left_little_1_joint.d: 0.0014
    gains.left_little_1_joint.i_clamp: 0.2
     
    command_interfaces: [position, velocity]  
    state_interfaces: [position, velocity]   

    # 容差参数
    goal_tolerance:
      position: 0.5
      velocity: 0.5

    # 状态发布频率
    state_publish_rate: 50.0

